Repository geotools/geotools, pull requests merged in 2019-09, with the labels that each got.

#2565 [GEOT-6372] Misaligned tile contents when rendering heterogenenous CRS mosaics, with reprojection, APH enabled, and high oversampling
  docs/src/main/java/org/geotools/main/FilterExamples.java
  modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/ReadResolutionCalculator.java
  modules/library/coverage/src/main/java/org/geotools/image/ImageWorker.java
  modules/library/coverage/src/test/java/org/geotools/coverage/grid/io/ReadResolutionCalculatorTest.java
  modules/library/render/src/test/resources/org/geotools/renderer/lite/gridcoverage2d/googleMercatorTouchDateline.png
  modules/library/render/src/test/resources/org/geotools/renderer/lite/gridcoverage2d/north_polar.png
  modules/library/render/src/test/resources/org/geotools/renderer/lite/gridcoverage2d/polar_touchdateline.png
  modules/library/render/src/test/resources/org/geotools/renderer/lite/gridcoverage2d/polar_whitecorner.png
  modules/library/render/src/test/resources/org/geotools/renderer/lite/gridcoverage2d/polar_whitecorner_up.png
  modules/library/render/src/test/resources/org/geotools/renderer/lite/gridcoverage2d/south_polar.png
  modules/library/render/src/test/resources/org/geotools/renderer/lite/gridcoverage2d/utm.png
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/hetero_utm_footprint_results/footprints.png
Labels: backport 21.x, backport 22.x

#2578 [GEOT-6397] Upgrading jgridshift to version 1.2
  modules/library/referencing/pom.xml
Labels: backport 22.x

#2583 [GEOT-6387] fix axis order in LatLonStrategy and related tests
  modules/unsupported/csv/src/main/java/org/geotools/data/csv/parse/CSVLatLonStrategy.java
  modules/unsupported/csv/src/test/java/org/geotools/data/csv/CSVDataStoreTest.java
  modules/unsupported/csv/src/test/java/org/geotools/data/csv/CSVWriteTest.java
  modules/unsupported/csv/src/test/java/org/geotools/data/csv/parse/CSVLatLonStrategyTest.java
  modules/unsupported/csv/src/test/java/org/geotools/data/csv/parse/CSVWriteStrategyTest.java
Labels: backport 21.x, backport 22.x

#2588 [GEOT-6388] Upgrade Jackson to 2.9.10
  pom.xml
Labels: backport 21.x, backport 22.x

#2582 GEOT-6018: WMTS doesn't correctly handle `image/jpeg` format
  modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/AbstractGetTileRequest.java
  modules/extension/wmts/src/test/java/org/geotools/ows/wmts/map/WMTSCoverageReaderTest.java
  modules/extension/wmts/src/test/resources/test-data/getcapa_kvp.xml
Labels: needs_cla
