Repository geotools/geotools, pull requests merged in 2022-10, with the labels that each got.

#4029 GEOT-7231: Z values shapefiles don't handle NaN M values correctly
  modules/library/main/src/main/java/org/geotools/geometry/jts/coordinatesequence/CoordinateSequences.java
  modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/MultiLineHandler.java
  modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/MultiPointHandler.java
  modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/PointHandler.java
  modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/PolygonHandler.java
  modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/shp/ZMHandlersTest.java
Labels: backport 27.x, backport 26.x

#4024 [GEOT-7226] ParameterTypeFactoryTest fails for certain locales
  modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/v2_0/storedquery/ParameterTypeFactoryTest.java
Labels: backport 27.x, backport 26.x

#4035 GEOT-7231] Z values shapefiles don't handle NaN M values correctly
  modules/library/main/src/main/java/org/geotools/geometry/jts/coordinatesequence/CoordinateSequences.java
  modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/MultiLineHandler.java
  modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/MultiPointHandler.java
  modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/PointHandler.java
  modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/PolygonHandler.java
  modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/shp/ZMHandlersTest.java
Labels: backport 27.x, backport 26.x

#4033 [GEOT-7233] Add support for sequences to SQL Server dialect
  modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDialect.java
  modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerPrimaryKeyOnlineTest.java
  modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerPrimaryKeyTestSetup.java
Labels: hacktoberfest-accepted, backport 27.x

#4048 Bump org.apache.commons:commons-text from 1.6 to 1.10.0
  modules/library/main/pom.xml
Labels: dependencies, backport 27.x, backport 26.x, backport 28.x

#4045 [GEOT-6259] ShapefileReadWriteTest fail on Windows
  modules/library/metadata/src/main/java/org/geotools/util/NIOUtilities.java
  modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureWriter.java
  modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/files/ShpFiles.java
  modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/files/ShpFilesLocker.java
  modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/files/StorageFile.java
  modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileReadWriteTest.java
Labels: backport 27.x, backport 26.x, backport 28.x

#4000 [GEOT-7210] YSLD styles do not set the layer name
  docs/user/extension/ysld.rst
  modules/extension/ysld/src/main/java/org/geotools/ysld/parse/RootParser.java
  modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseTest.java
Labels: backport 28.x

#4066 [GEOT-7210] YSLD does not encode layer name
  docs/user/extension/ysld.rst
  modules/extension/ysld/src/main/java/org/geotools/ysld/encode/RootEncoder.java
  modules/extension/ysld/src/main/java/org/geotools/ysld/parse/RootParser.java
  modules/extension/ysld/src/test/java/org/geotools/ysld/encode/YsldEncodeTest.java
  modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseTest.java
  modules/library/main/src/main/java/org/geotools/styling/SLD.java
Labels: backport 28.x

#4076 [GEOT-7247] ImageMosaic with RGBA images fails to respect transparency on overlaps
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/granulecollector/BaseSubmosaicProducer.java
  modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicReaderTest.java
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/alpha-overlap/one.tif
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/alpha-overlap/two.tif
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/rgba-overlap.png
Labels: backport 27.x, backport 26.x, backport 28.x

#4078 [GEOT-7246] Correctly handle null geometries in GeoJSON
  modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONWriter.java
  modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONWriteTest.java
Labels: backport 27.x, backport 28.x
