Repository geotools/geotools, pull requests merged in 2022-06, with the labels that each got.

#3920 [GEOT-7159] JDBCDataStore : some error messages are inconsistent
  modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
Labels: backport 21.x, backport 20.x

#3921 [GEOT-7109] Swt Module review and update
  docs/user/images/gtswt_rcp_01.png
  docs/user/images/gtswt_rcp_02.png
  docs/user/images/gtswt_standalone_01.png
  docs/user/images/gtswt_standalone_02.png
  docs/user/images/gtswt_standalone_03.png
  docs/user/unsupported/swt/index.rst
  docs/user/unsupported/swt/rcp.rst
  docs/user/unsupported/swt/swtmapframe.rst
  modules/unsupported/swt/pom.xml
  modules/unsupported/swt/src/main/java/org/geotools/swt/SwtMapFrame.java
  modules/unsupported/swt/src/main/java/org/geotools/swt/SwtMapPane.java
  modules/unsupported/swt/src/main/java/org/geotools/swt/action/ExitAction.java
  modules/unsupported/swt/src/main/java/org/geotools/swt/action/OpenGeotiffAction.java
  modules/unsupported/swt/src/main/java/org/geotools/swt/action/OpenShapefileAction.java
  modules/unsupported/swt/src/main/java/org/geotools/swt/control/CRSChooser.java
  modules/unsupported/swt/src/main/java/org/geotools/swt/control/ExceptionMonitor.java
  modules/unsupported/swt/src/main/java/org/geotools/swt/control/JParameterListWizard.java
  modules/unsupported/swt/src/main/java/org/geotools/swt/control/MaplayerTableViewer.java
  modules/unsupported/swt/src/main/java/org/geotools/swt/tool/GridLayerHelper.java
  modules/unsupported/swt/src/main/java/org/geotools/swt/utils/SwtActionsHandler.java
  modules/unsupported/swt/src/main/java/org/geotools/swt/utils/Utils.java
Labels: backport 27.x, backport 26.x

#3922 [GEOT-7161] Aggregate queries with non-database supported queries fail
  modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
  modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCAggregateFunctionOnlineTest.java
  modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCFeatureSourceOnlineTest.java
Labels: backport, backport 27.x, backport 26.x

#3928 [GEOT-7164] Make it easier to move mosaics of NetCDF around
  modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/AncillaryFileManager.java
  modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFMosaicReaderTest.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicConfigHandler.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterManager.java
Labels: backport 21.x, backport 20.x

#3932 [GEOT-7162] Postgis Partition tests fail on postgres versions below 11
  modules/library/sample-data/src/main/java/org/geotools/test/OnlineTestCase.java
  modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISPartitionedTest.java
  modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISPartitionedTestSetup.java
Labels: backport 27.x, backport 26.x

#3940 [Geot-7166] Fix jdbc informix failed tests
  modules/plugin/jdbc/jdbc-informix/src/main/java/org/geotools/data/informix/InformixDataStoreFactory.java
  modules/plugin/jdbc/jdbc-informix/src/test/java/org/geotools/data/informix/InformixAggregateFunctionOnlineTest.java
  modules/plugin/jdbc/jdbc-informix/src/test/java/org/geotools/data/informix/InformixTestSetup.java
Labels: backport 27.x

#3946 [GEOT-7171]: Remove iterator from Create (Since it's not used)
  modules/library/coverage/src/main/java/org/geotools/coverage/grid/RenderedSampleDimension.java
Labels: backport 27.x, backport 26.x

#3945 [GEOT-7170] StreamingRenderer might throw NPE with complex features when no default Geometry attribute is set
  modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java
  modules/library/render/src/test/java/org/geotools/renderer/lite/RenderableFeatureTest.java
Labels: backport 27.x, backport 26.x
