Repository geotools/geotools, pull requests merged in 2023-10, with the labels that each got.

#4502 [GEOT-7465] GML2EncodingUtils.toURI fails with the Web Service authority
  modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/bindings/GML2EncodingUtils.java
  modules/extension/xsd/xsd-gml2/src/test/java/org/geotools/gml2/bindings/GML2EncodingUtilsTest.java
Labels: backport 29.x, backport 30.x

#4476 [GEOT-7441] Upgrade sortpom plugin
  docs/pom.xml
  modules/extension/app-schema/app-schema/pom.xml
  modules/extension/complex/pom.xml
  modules/extension/wms/pom.xml
  modules/extension/xsd/xsd-core/pom.xml
  modules/extension/xsd/xsd-filter/pom.xml
  modules/extension/xsd/xsd-gml3/pom.xml
  modules/extension/ysld/pom.xml
  modules/library/coverage/pom.xml
  modules/library/cql/pom.xml
  modules/library/http/pom.xml
  modules/library/jdbc/pom.xml
  modules/library/main/pom.xml
  modules/library/referencing/pom.xml
  modules/library/render/pom.xml
  modules/plugin/coverage-multidim/netcdf/pom.xml
  modules/plugin/http-commons/pom.xml
  modules/plugin/imageio-ext-gdal/pom.xml
  modules/plugin/imagemosaic/pom.xml
  modules/plugin/jdbc/jdbc-h2/pom.xml
  modules/unsupported/cql2/pom.xml
  modules/unsupported/elasticsearch/pom.xml
  modules/unsupported/mbtiles/pom.xml
  modules/unsupported/ogr/ogr-core/pom.xml
  modules/unsupported/process-raster/pom.xml
  modules/unsupported/solr/pom.xml
  modules/unsupported/wps/pom.xml
  pom.xml
  release/pom.xml
Labels: backport 28.x, backport 29.x

#4513 [GEOT-7434] ElasticSearch throws repeated point exceptions on small bbox filters
  modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/FilterToElastic.java
  modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticFeatureFilterIT.java
  modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticFilterTest.java
  modules/unsupported/geojson-core/src/main/java/com/bedatadriven/jackson/datatype/jts/JtsModule.java
  modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONWriter.java
  modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONWriteTest.java
  modules/unsupported/geojson-store/src/test/java/org/geotools/data/geojson/store/AxisOrderTest.java
  modules/unsupported/geojson-store/src/test/java/org/geotools/data/geojson/store/GeoJSONWriteTest.java
Labels: backport 29.x, backport 30.x

#4519 [GEOT-7472] Update bin download for gt-api and java 11
  .github/workflows/assembly.yml
  .github/workflows/linux_jdk11.yml
  .github/workflows/linux_jdk17.yml
  release/README.md
  release/pom.xml
  release/src/assembly/binaryDistDependencies.xml
  release/src/markdown/README.md
  release/src/markdown/html/footer.html
Labels: backport 30.x

#4530 [GEOT-7480] SumVisitor NPE When Value from Database is Null
  modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCGroupByVisitorOnlineTest.java
  modules/library/main/src/main/java/org/geotools/feature/visitor/Aggregate.java
  modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgGroupByVisitorTestSetup.java
  modules/plugin/jdbc/jdbc-db2/src/test/java/org/geotools/data/db2/DB2GroupByVisitorTestSetup.java
  modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2GroupByVisitorTestSetup.java
  modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaGroupByVisitorTestSetup.java
  modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLGroupByVisitorTestSetup.java
  modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleGroupByVisitorTestSetup.java
  modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisGroupByVisitorTestSetup.java
  modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerGroupByVisitorTestSetup.java
  modules/unsupported/jdbc-h2gis/src/test/java/org/h2gis/geotools/H2GISGroupByVisitorTestSetup.java
Labels: backport 29.x, backport 30.x
