Repository geotools/geotools, pull requests merged in 2023-04, with the labels that each got.

#4255 [GEOT-7338] Fix XML container element duplicates child attributes
  modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/DefaultGeometryTest.java
  modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/measurementsDefaultGeometry.xml
  modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/measurementsDefaultGeometry.xsd
  modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/stationsDefaultGeometry.xml
  modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/stationsDefaultGeometry.xsd
  modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/bindings/ComplexSupportXSAnyTypeBinding.java
Labels: backport 27.x, backport 26.x, backport 28.x, backport 29.x

#4264 [Backport 27.x] Bump json from 20210307 to 20230227 in /modules/unsupported/flatgeobuf
  modules/unsupported/flatgeobuf/pom.xml
Labels: dependencies

#4267 [Backport 29.x] Bump json from 20210307 to 20230227 in /modules/unsupported/flatgeobuf
  modules/unsupported/flatgeobuf/pom.xml
Labels: dependencies

#4266 [Backport 28.x] Bump json from 20210307 to 20230227 in /modules/unsupported/flatgeobuf
  modules/unsupported/flatgeobuf/pom.xml
Labels: dependencies

#4265 [Backport 26.x] Bump json from 20210307 to 20230227 in /modules/unsupported/flatgeobuf
  modules/unsupported/flatgeobuf/pom.xml
Labels: dependencies

#4220 [GEOT-7322] WFSContentComplexFeatureCollection.subCollection doesn't use the filter
  modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/ComplexGetFeatureResponse.java
  modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSContentComplexFeatureCollection.java
  modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XmlComplexFeatureParser.java
  modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSourceTest.java
Labels: backport 27.x, backport 28.x, backport 29.x

#4274 [GEOT-7344] Child feature ClientProperties are duplicated on no-GML XML element parent container from the child elements
  modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/DataAccessMappingFeatureIterator.java
  modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/AbstractStationsTest.java
  modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/ClientPropertiesNoDuplicatesTest.java
  modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/DefaultGeometryTest.java
  modules/extension/app-schema/app-schema/src/test/resources/test-data/stations-nestednogml/measurementsDefaultGeometry.properties
  modules/extension/app-schema/app-schema/src/test/resources/test-data/stations-nestednogml/measurementsDefaultGeometry.xml
  modules/extension/app-schema/app-schema/src/test/resources/test-data/stations-nestednogml/measurementsDefaultGeometry.xsd
  modules/extension/app-schema/app-schema/src/test/resources/test-data/stations-nestednogml/measurementsManyToOne.properties
  modules/extension/app-schema/app-schema/src/test/resources/test-data/stations-nestednogml/stationsDefaultGeometry.properties
  modules/extension/app-schema/app-schema/src/test/resources/test-data/stations-nestednogml/stationsDefaultGeometry.xml
  modules/extension/app-schema/app-schema/src/test/resources/test-data/stations-nestednogml/stationsDefaultGeometry.xsd
  modules/extension/app-schema/app-schema/src/test/resources/test-data/stations-nestednogml/stationsDefaultGeometryNonExistentProperty.xml
  modules/extension/app-schema/app-schema/src/test/resources/test-data/stations-nestednogml/stationsDefaultGeometryWrongType.xml
  modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/bindings/ComplexSupportXSAnyTypeBinding.java
Labels: backport 27.x, backport 28.x, backport 29.x

#4263 [GEOT-7340] Avoid PAMParser init causing ImageMosaic to fail
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
Labels: backport 27.x, backport 28.x, backport 29.x
