Repository geotools/geotools, pull requests merged in 2023-11, with the labels that each got.

#4472 [GEOT-7430] WFSContentDataAccess should download local copy
  modules/library/xml/src/main/java/org/geotools/xml/resolver/SchemaResolver.java
  modules/unsupported/wfs-ng/pom.xml
  modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSContentDataAccess.java
  modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/impl/WFSContentDataAccessTest.java
  modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/KartverketStedsnavnDataStoreOnlineTest.java
Labels: backport 29.x, backport 30.x

#4537 [GEOT-7486] CSS literal single space squashed to empty string
  modules/library/xml/src/main/java/org/geotools/xml/transform/TransformerBase.java
  modules/library/xml/src/test/java/org/geotools/xml/styling/SLDTransformerTest.java
Labels: backport 29.x, backport 30.x

#4536 [GEOT-7488] GDAL, GeoTIFF and ImageMosaic ignore nodata when it's NaN
  modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/imageio/geotiff/GeoTiffIIOMetadataDecoder.java
  modules/library/render/src/test/java/org/geotools/renderer/lite/GridCoverageRendererTest.java
  modules/library/render/src/test/resources/org/geotools/renderer/lite/gridcoverage2d/sampleGrib.png
  modules/library/render/src/test/resources/org/geotools/renderer/lite/gridcoverage2d/sampleGribCropLongitude.png
  modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffReader.java
  modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffReaderTest.java
  modules/plugin/imageio-ext-gdal/src/main/java/org/geotools/coverageio/RasterLayerResponse.java
  modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/vrt/VRTTest.java
  modules/plugin/imageio-ext-gdal/src/test/resources/org/geotools/coverageio/gdal/vrt/test-data/n43.dt0.nan.vrt
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterLayerResponse.java
  modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicRATTest.java
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/bluetopo/indexer.properties
Labels: backport 29.x, backport 30.x

#4542 [GEOT-7485] Double Check ReferencedEnvelope against Rectangle2D.Double() expectations
  modules/library/main/src/main/java/org/geotools/geometry/jts/ReferencedEnvelope.java
  modules/library/main/src/test/java/org/geotools/geometry/jts/ReferencedEnvelopeTest.java
Labels: backport 30.x

#4544 [GEOT-7490] WPS Intersection NPE when the Return Value Should be a Point
  modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/IntersectionFeatureCollection.java
  modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/IntersectionFeatureCollectionTest.java
Labels: backport 29.x, backport 30.x

#4552 [GEOT-7491] ShapeFileDataStore should use GeometryFactory of DataStore
  modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureSource.java
  modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreSetGeometryFactoryTest.java
Labels: backport 28.x, backport 29.x, backport 30.x

#4557 Upgrade flatgeobuf to 3.26.2
  modules/unsupported/flatgeobuf/pom.xml
  modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java
Labels: backport 29.x, backport 30.x

#4561 [GEOT-7495] Correct Hints.REPOSITORY reference org.geotools.api.data.Repository
  modules/library/metadata/src/main/java/org/geotools/util/factory/Hints.java
Labels: backport 30.x

#4564 [GEOT-7498] Upgrade DB2 JDBC driver from 11.5.6.0 to 11.5.9.0
  pom.xml
Labels: backport 29.x, backport 30.x
