Repository geotools/geotools, pull requests merged in 2023-03, with the labels that each got.

#4208 [GEOT-7316] Child feature ClientProperties are replicated on GML parent container elements
  modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/bindings/FeaturePropertyTypeBinding.java
  modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/GML3EncodingTest.java
  modules/extension/xsd/xsd-wfs/src/test/java/org/geotools/wfs/v2_0/WFSFeatureCollectionEncodingTest.java
Labels: backport 27.x, backport 26.x, backport 28.x

#4202 [GEOT-7310] Update Oracle JDBC driver to 19.18.0.0
  build/ci/oracle/start-oracle.sh
  pom.xml
Labels: backport 27.x, backport 28.x

#4223 [Backport 28.x] [GEOT-7317] Upgrade snakeyaml from 1.32 to to 2.0
  modules/extension/ysld/pom.xml
  modules/extension/ysld/src/main/java/org/geotools/ysld/YamlUtil.java
  modules/extension/ysld/src/main/java/org/geotools/ysld/encode/YsldRepresenter.java
  modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseTest.java
Labels: dependencies

#4222 [Backport 27.x] [GEOT-7317] Upgrade snakeyaml from 1.32 to to 2.0
  modules/extension/ysld/pom.xml
  modules/extension/ysld/src/main/java/org/geotools/ysld/YamlUtil.java
  modules/extension/ysld/src/main/java/org/geotools/ysld/encode/YsldRepresenter.java
  modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseTest.java
Labels: dependencies

#4224 [Backport 29.x] [GEOT-7317] Upgrade snakeyaml from 1.32 to to 2.0
  modules/extension/ysld/pom.xml
  modules/extension/ysld/src/main/java/org/geotools/ysld/YamlUtil.java
  modules/extension/ysld/src/main/java/org/geotools/ysld/encode/YsldRepresenter.java
  modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseTest.java
Labels: dependencies

#4227 [GEOT-7327] TransformFeatureSource needs to transform FID filters too
  modules/extension/transform/src/main/java/org/geotools/data/transform/TransformFilterVisitor.java
  modules/extension/transform/src/main/java/org/geotools/data/transform/Transformer.java
  modules/extension/transform/src/test/java/org/geotools/data/transform/TransformFeatureSourceTest.java
  modules/extension/transform/src/test/java/org/geotools/data/transform/TransformerTest.java
Labels: backport 27.x, backport 28.x, backport 29.x

#4234 [GEOT-7325] fix NPE on REST template requests with no operations
  modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WebMapTileServer.java
  modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WebMapTileServerTest.java
Labels: backport 28.x, backport 29.x
