Repository geotools/geotools, pull requests merged in 2023-08, with the labels that each got.

#4405 [GEOT-7404] Add SQLite Connection Timeout in case of hung GeoPackage connections
  modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDataStoreFactory.java
  modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDataStoreFactoryTest.java
Labels: backport 28.x, backport 29.x

#4406 [GEOT-7406] Vector Mosaic Cache granule connection in memory to avoid redundant initialization and improve granule iterator cleanup
  modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/GranuleStoreFinder.java
  modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/GranuleStoreFinderImpl.java
  modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/GranuleTracker.java
  modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureReader.java
  modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
  modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicGranule.java
  modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicGranuleStoreFinderMonitoring.java
  modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicReaderTest.java
Labels: backport 28.x, backport 29.x

#4411 [GEOT-7410] Vector Mosaic optimize aggregate queries that hit only th…
  modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
  modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
  modules/unsupported/vector-mosaic/src/test/resources/org.geotools.vectormosaic.data/granule1.dbf
  modules/unsupported/vector-mosaic/src/test/resources/org.geotools.vectormosaic.data/granule2.dbf
  modules/unsupported/vector-mosaic/src/test/resources/org.geotools.vectormosaic.data/granule3.dbf
  modules/unsupported/vector-mosaic/src/test/resources/org.geotools.vectormosaic.data/mosaic_delegate.dbf
Labels: backport 28.x, backport 29.x

#4416 [GEOT-7416] org.geotools.feature.NameImpl.compareTo creates garbage objects
  modules/library/main/src/main/java/org/geotools/feature/NameImpl.java
  modules/library/main/src/test/java/org/geotools/feature/NameImplTest.java
Labels: backport 29.x

#4408 [GEOT-7407] Vector Mosaic Cache granuleFeatureType at DataStore and improve granule FeatureType acquisition
  modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
  modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicState.java
  modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicStore.java
  modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
Labels: backport 28.x, backport 29.x

#4427 [GEOT-7420] Vector mosaic reader: do not recompute the schema for every feature read
  modules/unsupported/vector-mosaic/pom.xml
  modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureReader.java
  modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
  modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicReaderTest.java
Labels: backport 28.x, backport 29.x

#4423 [GEOT-7421] Caching WKT parsing results
  modules/library/referencing/src/main/java/org/geotools/referencing/CRS.java
Labels: backport 29.x

#4434 [GEOT-7425] Add support for extended colorMap in CSS
  modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
  modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
Labels: backport 28.x, backport 29.x

#4437 Bump org.springframework.security:spring-security-core to 5.7.10
  modules/unsupported/elasticsearch/pom.xml
Labels: dependencies, backport 28.x, backport 29.x
