Repository geotools/geotools, pull requests merged in 2024-10, with the labels that each got.

#4942 [GEOT-7665] PointStacker envBBOX has wrong value
  modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/PointStackerProcess.java
  modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/PointStackerProcessTest.java
Labels: backport 31.x, backport 32.x

#4947 [GEOT-7666] Parsing empty Rotation style element throws a ClassCastException
  modules/extension/xsd/xsd-sld/src/main/java/org/geotools/sld/bindings/SLDGraphicBinding.java
  modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDGraphicBindingTest.java
  modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDMockData.java
Labels: backport 31.x, backport 32.x

#4956 bump commons-io:commons-io to 2.17.0
  pom.xml
Labels: backport 32.x

#4961 [GEOT-7671] Vector mosaic 'count' implementation does not account for max features
  modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/GranuleSourceProvider.java
  modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
  modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
Labels: backport 31.x, backport 32.x

#4948 [GEOT-7667] JDBCDataStore getAggregateValue is not JSONPointer aware when splitting the filters
  modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
  modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCDataStoreTest.java
  modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISJsonOnlineTest.java
Labels: backport 31.x, backport 32.x

#4964 GEOT-7672:ElasticSearch date converter:Fixing day of month support
  modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/date/ElasticsearchDateConverter.java
  modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/date/ElasticsearchDateConverterParseTest.java
Labels: backport 27.x, backport 26.x

#4955 [GEOT-7669] ConcurrentModificationException in WMSCapabilities.getLayerList()
  modules/extension/wms/src/main/java/org/geotools/ows/wms/WMSCapabilities.java
  modules/extension/wms/src/test/java/org/geotools/ows/wms/WMSCapabilitiesTest.java
Labels: backport 31.x, backport 32.x

#4974 [GEOT-7674] Shapefile performance/memory usage regression: the DBF fi…
  modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileSetManager.java
  modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/dbf/DbaseFileHeader.java
  modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreTest.java
Labels: backport 31.x, backport 32.x

#4976 [GEOT-7664] Use CQL2 related module names fro release and stac-store dependencies
  modules/unsupported/stac-store/pom.xml
  release/pom.xml
Labels: backport 31.x, backport 32.x
