Repository geotools/geotools, pull requests merged in 2024-12, with the labels that each got.

#4293 [GEOT-7234] Implement #getOptimizedBounds(...) in SQLServerDialect
  modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDataStoreFactory.java
  modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDialect.java
  modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerDialectOnlineTest.java
  modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerDialectTestSetup.java
Labels: backport 31.x, backport 32.x

#4998 [GEOT-7693] CenterLine process can leave gaps in the skeletonisation
  modules/unsupported/process-geometry/src/main/java/org/geotools/process/geometry/Skeletonize.java
  modules/unsupported/process-geometry/src/test/java/org/geotools/process/geometry/CenterLineTest.java
Labels: backport 31.x, backport 32.x

#5016 [GEOT-7694] Update MySQL driver to 9.1.0
  modules/plugin/jdbc/jdbc-mysql/pom.xml
  pom.xml
Labels: backport 31.x, backport 32.x

#5018 [Backport 31.x] [GEOT-7694] Update MySQL driver to 9.1.0
  modules/plugin/jdbc/jdbc-mysql/pom.xml
  pom.xml
Labels: dependencies

#5019 Upgrade wiremock from 2.35.1 to 3.10.0
  modules/library/http/pom.xml
  modules/library/http/src/test/java/org/geotools/http/SimpleHttpClientTest.java
  modules/library/xml/pom.xml
  modules/library/xml/src/test/java/org/geotools/xml/resolver/SchemaCacheTest.java
  modules/plugin/http-commons/pom.xml
  modules/plugin/http-commons/src/test/java/org/geotools/http/commons/MultithreadedHttpClientTest.java
  modules/unsupported/stac-store/pom.xml
  modules/unsupported/stac-store/src/test/java/org/geotools/stac/store/STACDataStoreFactoryTest.java
  pom.xml
Labels: backport 32.x

#5024 only use jts snapshot repo when requested with jts profile
  pom.xml
Labels: backport 32.x
