Repository geotools/geotools, pull requests merged in 2024-06, with the labels that each got.

#4796 [GEOT-7556] Just build javadocs for modules, and mvn javadoc doclint config
  .github/workflows/assembly.yml
  pom.xml
Labels: backport 29.x, backport 30.x, backport 31.x

#4797 [GEOT-7587] Improve handling of XPath expressions
  modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/util/XmlXpathUtilites.java
  modules/extension/app-schema/app-schema/src/test/java/org/geotools/appschema/util/XmlXpathUtilitesTest.java
  modules/extension/complex/src/main/java/org/geotools/data/complex/expression/FeaturePropertyAccessorFactory.java
  modules/extension/complex/src/main/java/org/geotools/data/complex/expression/MapPropertyAccessorFactory.java
  modules/extension/complex/src/test/java/org/geotools/filter/expression/FeaturePropertyAccessorTest.java
  modules/extension/complex/src/test/java/org/geotools/filter/expression/MapPropertyAccessorTest.java
  modules/extension/xsd/xsd-core/pom.xml
  modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/jxpath/JXPathStreamingParserHandler.java
  modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/jxpath/JXPathUtils.java
  modules/extension/xsd/xsd-core/src/test/java/org/geotools/xsd/StreamingParserTest.java
Labels: backport 30.x, backport 31.x

#4804 [29.x backport] [GEOT-7587] Improve handling of XPath expressions
  modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/util/XmlXpathUtilites.java
  modules/extension/app-schema/app-schema/src/test/java/org/geotools/appschema/util/XmlXpathUtilitesTest.java
  modules/extension/complex/src/main/java/org/geotools/data/complex/expression/FeaturePropertyAccessorFactory.java
  modules/extension/complex/src/main/java/org/geotools/data/complex/expression/MapPropertyAccessorFactory.java
  modules/extension/complex/src/test/java/org/geotools/filter/expression/FeaturePropertyAccessorTest.java
  modules/extension/complex/src/test/java/org/geotools/filter/expression/MapPropertyAccessorTest.java
  modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/jxpath/JXPathStreamingParserHandler.java
  modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/jxpath/JXPathUtils.java
  modules/extension/xsd/xsd-core/src/test/java/org/geotools/xsd/StreamingParserTest.java
Labels: backport 28.x

#4811 [GEOT-7597] Upgrade to ImageIO-EXT 1.4.12
  pom.xml
Labels: backport 30.x, backport 31.x

#4807 [GEOT-7590] Fix ampersand handling in Like filters
  modules/library/main/src/main/java/org/geotools/filter/LikeToRegexConverter.java
  modules/library/main/src/test/java/org/geotools/filter/LikeFilterImplTest.java
Labels: backport 30.x, backport 31.x

#4819 [GEOT-7607] Error using function Interpolate in COLOR mode from SLD
  modules/library/main/src/main/java/org/geotools/filter/function/InterpolateFunction.java
  modules/library/main/src/test/java/org/geotools/filter/function/InterpolateFunctionTest.java
Labels: backport 31.x

#4816 [GEOT-7599] Update MySQL CI matrix (drop 5.7, add 8.4)
  .github/workflows/mysql_online.yml
Labels: backport 31.x

#4810 [GEOT-7596] Reduce chance of white line artifacts when performing high subsampling on read
  modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/AbstractGridCoverage2DReader.java
  modules/library/coverage/src/main/java/org/geotools/image/util/ImageUtilities.java
  modules/plugin/coverage-multidim/coverage-api/src/main/java/org/geotools/coverage/io/util/Utilities.java
  modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/NetCDFResponse.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ReadParamsController.java
  modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicFootprintsTest.java
  modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicReaderTest.java
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/egr-all-desc-raster.png
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/egr-all-desc-vector.png
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/egr-alpha-hetero-fade.png
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/egr-alpha-hetero.png
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/egr-red-covers-all-raster.png
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/egr-red-covers-all-vector.png
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/hetero_crs_dateline_results/before.png
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/no-slivers.png
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sample_image.dat
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver.dbf
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver.fix
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver.prj
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver.properties
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver.shp
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver.shx
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver_1.tif
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver_10.tif
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver_11.tif
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver_12.tif
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver_2.tif
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver_3.tif
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver_4.tif
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver_5.tif
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver_6.tif
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver_7.tif
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver_8.tif
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/sliver/sliver_9.tif
  modules/plugin/jp2k/src/main/java/org/geotools/coverageio/jp2k/RasterManager.java
Labels: backport 31.x

#4823 [GEOT-7607] Error using function Interpolate in COLOR mode from SLD
  modules/library/main/src/main/java/org/geotools/filter/function/InterpolateFunction.java
  modules/library/main/src/test/java/org/geotools/filter/function/InterpolateFunctionTest.java
Labels: backport 30.x, backport 31.x
