Repository geotools/geotools, pull requests merged in 2025-02, with the labels that each got.

#5074 Upgrade PostgreSQL driver from 42.7.3 to 42.7.5
  pom.xml
Labels: backport 31.x, backport 32.x

#5077 Upgrade commons-lang3 from 3.15.0 to 3.17.0
  modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCDataStoreOnlineTest.java
  modules/plugin/jdbc/jdbc-informix/src/test/java/org/geotools/data/informix/InformixDataStoreOnlineTest.java
  modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSContentDataAccess.java
  pom.xml
Labels: backport 31.x, backport 32.x

#5075 Upgrade guava from 33.2.1 to 33.4.0
  pom.xml
Labels: backport 31.x, backport 32.x

#5076 Upgrade commons-io from 2.17.0 to 2.18.0
  modules/extension/graph/src/main/java/org/geotools/graph/io/standard/SerializedReaderWriter.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/Utils.java
  pom.xml
Labels: dependencies, backport 31.x, backport 32.x

#5082 [GEOT-7717] Updating GDAL to latest, 3.10.1
  .github/workflows/macos.yml
Labels: backport 31.x, backport 32.x

#5085 Upgrade mockito from 5.12.0 to 5.15.2
  pom.xml
Labels: backport 31.x, backport 32.x

#5091 Upgrade wiremock from 3.10.0 to 3.11.0
  pom.xml
Labels: backport 31.x, backport 32.x

#5090 Upgrade commons-text from 1.12.0 to 1.13.0
  pom.xml
Labels: backport 31.x, backport 32.x

#5101 Upgrade junit-upiter from 5.8.2 to 5.11.4
  modules/unsupported/jdbc-h2gis/pom.xml
  pom.xml
Labels: backport 32.x

#5099 Upgrade commons-logging from 1.2 to 1.3.5
  modules/library/metadata/src/test/java/org/geotools/util/factory/GeoToolsTest.java
  pom.xml
Labels: backport 32.x

#5105 [GEOT-7718] make the parsing of LogoURL lenient
  modules/extension/wms/src/main/java/org/geotools/ows/wms/xml/WMSComplexTypes.java
  modules/extension/wms/src/test/java/org/geotools/ows/wms/test/WMS1_3_0_Test.java
  modules/extension/wms/src/test/resources/org/geotools/ows/wms/test/test-data/ign.xml
Labels: backport 31.x, backport 32.x

#5098 Upgrade commons-beanutils from 1.9.4 to 1.10.1
  pom.xml
Labels: dependencies, backport 32.x

#5100 Upgrade batik from 1.17 to 1.18
  pom.xml
Labels: dependencies, backport 32.x

#5106 [GEOT-7719] The Jiffle process ignores input images nodata
  modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/JiffleProcess.java
  modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/JiffleProcessTest.java
  pom.xml
Labels: backport 32.x

#5072 [GEOT-7320] ServiceException from a WFS server GetFeature ends in a FactoryNotFoundException
  modules/library/main/src/main/java/org/geotools/data/ows/Response.java
  modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/TransactionRequest.java
  modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSExtensions.java
  modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSRequest.java
  modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSResponseFactory.java
  modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/AbstractWFSResponseFactory.java
  modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/ServiceExceptionResponseFactory.java
  modules/unsupported/wfs-ng/src/main/resources/META-INF/services/org.geotools.data.wfs.internal.WFSResponseFactory
  modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/integration/IntegrationTestWFSClient.java
  modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/integration/v1_1/XXEProtectionTest.java
  modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/WFSResponseFactoryTest.java
Labels: backport 31.x, backport 32.x
