Repository geotools/geotools, pull requests merged in 2025-05, with the labels that each got.

#5188 [GEOT-7756] Communication update address outdated http, irc, project and corporate links
  docs/developer/communication.rst
  docs/developer/procedures/build_server.rst
  docs/developer/procedures/release.rst
  docs/user/build/maven/snapshots.rst
  docs/user/welcome/support.rst
Labels: backport 31.x, backport 32.x, backport 33.x

#5192 Use all cores in github actions, most sport 4 nowadays
  .github/workflows/assembly.yml
  .github/workflows/cql2_online.yml
  .github/workflows/db2_online.yml
  .github/workflows/elasticsearch_online.yml
  .github/workflows/geopkg_online.yml
  .github/workflows/informix.yml
  .github/workflows/integration.yml
  .github/workflows/linux_jdk11.yml
  .github/workflows/linux_jdk17.yml
  .github/workflows/linux_jdk21.yml
  .github/workflows/macos.yml
  .github/workflows/mssql_online.yml
  .github/workflows/mysql_online.yml
  .github/workflows/oracle_online.yml
  .github/workflows/postgis_online.yml
  .github/workflows/windows.yml
Labels: backport 32.x, backport 33.x

#5200 Fix Eclipse maven integration for non-standard source folders in modules/ogc/pom.xml
  modules/ogc/net.opengis.wmts/build.properties
  modules/ogc/net.opengis.wmts/pom.xml
Labels: backport 33.x
