Repository geotools/geotools, pull requests merged in 2025-01, with the labels that each got.

#5041 [GEOT-7703] Allow usage of fullPath in most common mosaic property collectors
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/DefaultPropertiesCollectorSPI.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/FullPathCollector.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/RegExPropertiesCollector.java
  modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/properties/string/StringFileNameExtractorTest.java
Labels: backport 32.x

#5034 [GEOS-7698] GeoTIFF and image mosaic do not handle COGs with masks properly
  modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/footprint/MultiLevelROIRaster.java
  modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/imageio/MaskOverviewProvider.java
  modules/library/sample-data/pom.xml
  modules/library/sample-data/src/main/java/org/geotools/test/wiremock/FileRangeResponseTransformer.java
  modules/plugin/geotiff/pom.xml
  modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffReader.java
  modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTIFFReaderMaskCOGTest.java
  modules/plugin/geotiff/src/test/resources/org/geotools/gce/geotiff/test-data/mask/masked2cog.tif
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/CogGranuleAccessProvider.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/DefaultGranuleAccessProvider.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicReader.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/Utils.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/catalog/MultiLevelROIProviderMosaicFactory.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/catalog/MultiLevelROIRasterProvider.java
  modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicCogMaskTest.java
  modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/TestUtils.java
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/masked2cog.tif
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/masked2cog/datastore.properties
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/masked2cog/footprints.properties
  modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/masked2cog/indexer.properties
Labels: backport 31.x, backport 32.x

#5045 [GEOT-7704] Replace commons-httpclient with httpcomponents:httpclient
  modules/unsupported/arcgis-rest/pom.xml
  modules/unsupported/arcgis-rest/src/main/java/org/geotools/data/arcgisrest/ArcGISRestDataStore.java
  modules/unsupported/arcgis-rest/src/main/java/org/geotools/data/arcgisrest/ArcGISRestFeatureSource.java
  modules/unsupported/arcgis-rest/src/test/java/org/geotools/data/arcgisrest/ArcGISRestDataStoreTest.java
Labels: dependencies, backport 32.x

#5053 Bump org.eclipse.jetty:jetty-server from 9.4.55.v20240627 to 9.4.57.v20241219 in /modules/extension/app-schema/app-schema
  modules/extension/app-schema/app-schema/pom.xml
Labels: dependencies, backport 31.x, backport 32.x

#5061 [GEOT-7545] Wrong log level comparison in LogbackLogger#isLoggable
  modules/library/metadata/src/main/java/org/geotools/util/logging/LogbackLogger.java
  modules/library/metadata/src/test/java/org/geotools/util/logging/LoggingTest.java
Labels: backport 31.x, backport 32.x

#5067 [GEOT-7712] Update JAI-Ext to 1.1.28
  pom.xml
Labels: backport 31.x, backport 32.x
