Repository geotools/geotools, pull requests merged in 2025-06, with the labels that each got.

#5212 upgrade postgresql to 42.7.6
  pom.xml
Labels: backport 32.x, backport 33.x

#5207 [GEOT-7765] Improve PropertyIsLike filter to work for numeric columns in postgres
  modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
  modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisFilterToSQL.java
  modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisFilterToSQLTest.java
Labels: backport 27.x, backport 26.x

#5221 Upgrade guava from 33.4.0 to 33.4.8
  modules/unsupported/mbtiles/pom.xml
  pom.xml
Labels: dependencies, backport 33.x

#5227 [GEOT-7773] GeoJSONParser of gt-arcgisrest sets Id of each feature to "features"
  modules/unsupported/arcgis-rest/src/main/java/org/geotools/data/arcgisrest/GeoJSONParser.java
  modules/unsupported/arcgis-rest/src/test/java/org/geotools/data/arcgisrest/GeoJSONParserTest.java
Labels: backport 33.x

#5216 Upgrade snakeyaml from 2.3 to 2.4
  pom.xml
Labels: dependencies, backport 33.x

#5217 Upgrade jackson from 2.18.2 to 2.19.0
  modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONReader.java
  pom.xml
Labels: dependencies, backport 32.x, backport 33.x

#5202 [GEOT-7767] Java UUID type support to geopkg dialect
  modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java
  modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
Labels: backport 32.x, backport 33.x

#5242 [GEOT-7776] Image mosaic property collectors fail with a array access exception when the regex does not match
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/RegExPropertiesCollector.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/numeric/NumericFileNameExtractor.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/string/StringFileNameExtractor.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/time/TimestampFileNameExtractor.java
  modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/properties/numeric/NumericFileNameExtractorTest.java
  modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/properties/string/StringFileNameExtractorTest.java
  modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/properties/time/TimestampFileNameExtractorTest.java
Labels: backport 32.x, backport 33.x

#5252 [GEOT-7780] Contrast enhancement with clip to min/max loses input nodata
  modules/library/coverage/src/main/java/org/geotools/image/ImageWorker.java
  modules/library/render/src/test/java/org/geotools/renderer/lite/gridcoverage2d/RasterSymbolizerTest.java
  modules/library/render/src/test/java/org/geotools/renderer/lite/gridcoverage2d/TestPiecewise.java
Labels: backport 32.x, backport 33.x

#5262 Fix Hive partitioning with query parameters in the uri
  docs/user/unsupported/geoparquet.rst
  modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/HivePartitionResolver.java
  modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/HivePartitionResolverTest.java
Labels: backport 33.x

#5253 [GEOT-7781] Add a priority to property accessors
  modules/extension/complex/src/main/java/org/geotools/data/complex/expression/FeaturePropertyAccessorFactory.java
  modules/library/main/src/main/java/org/geotools/filter/expression/PropertyAccessorFactory.java
  modules/library/main/src/main/java/org/geotools/filter/expression/PropertyAccessors.java
  modules/library/main/src/test/java/org/geotools/filter/expression/PropertyAccessorsFactoryTest.java
  modules/library/main/src/test/resources/META-INF/services/org.geotools.filter.expression.PropertyAccessorFactory
Labels: backport 32.x, backport 33.x
