Repository geotools/geotools, pull requests merged in 2025-03, with the labels that each got.

#5117 [GEOT-7721] Oracle datastore does not handle NCLOB
  modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java
  modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleNClobConverterFactory.java
  modules/plugin/jdbc/jdbc-oracle/src/main/resources/META-INF/services/org.geotools.util.ConverterFactory
  modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleLobOnlineTest.java
  modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleLobTestSetup.java
Labels: backport 32.x

#5118 [GEOT-7723] Upgrade Oracle JDBC driver (ojdbc) from 8 to 11
  modules/plugin/jdbc/jdbc-oracle/pom.xml
  pom.xml
Labels: dependencies, backport 32.x

#5123 [GEOT-7725] Upgrade DB2 JDBC driver from 11.5.9.0 to 12.1.0.0
  pom.xml
Labels: dependencies, backport 32.x

#5122 [GEOT-7724] Improve validation when deserializing objects
  docs/user/library/coverage/mosaic.rst
  docs/user/welcome/upgrade.rst
  modules/library/coverage/src/main/java/org/geotools/coverage/grid/GridCoverage2D.java
  modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/Utils.java
  modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/UtilsTest.java
  modules/plugin/imagepyramid/src/test/resources/org/geotools/gce/imagepyramid/test-data/timepyramid/0/sample_image
  modules/plugin/imagepyramid/src/test/resources/org/geotools/gce/imagepyramid/test-data/timepyramid/1/sample_image
  modules/plugin/imagepyramid/src/test/resources/org/geotools/gce/imagepyramid/test-data/timepyramid/2/sample_image
Labels: backport 32.x

#5128 [GEOT-7729] Update jai-ext to 1.1.30
  pom.xml
Labels: dependencies, backport 32.x

#5132 [GEOT-7734] Update to jai-ext 1.1.31
  pom.xml
Labels: backport 31.x, backport 32.x

#5133 [GEOT-7735] Upgrade ImageIO-EXT to 1.4.15
  pom.xml
Labels: backport 32.x
